version: "3.8"

services:
  web:
    image: 535793255376.dkr.ecr.us-east-1.amazonaws.com/customer-order:latest
    container_name: savannah-api
    build:
      context: .
      dockerfile: Dockerfile-prod
    command: gunicorn savanah.wsgi:application --bind 0.0.0.0:8000
#    volumes:
#      - static_volume:/home/app/api/static
#      - media_volume:/home/app/api/static/media
    expose:
      - "8000"
    env_file:
      - ./.env.prod
    networks:
      - savannah
  nginx:
    image: 535793255376.dkr.ecr.us-east-1.amazonaws.com/ngnix:latest
    build: ./nginx
    ports:
      - "1337:80"
    volumes:
      - static_volume:/home/app/api/static
      - media_volume:/home/app/api/static/media
    links:
      - web:web
    depends_on:
      - web
    networks:
      - savannah

volumes:
#  database-data:
  static_volume:
  media_volume:
networks:
  savannah: