version: "3.8"

services:
  web:
    image: 535793255376.dkr.ecr.us-east-1.amazonaws.com/customer-order:latest
    container_name: savannah-api
    build:
      context: .
      dockerfile: Dockerfile-prod
    ports:
      - "8000:80"
    env_file:
      - prod.env
