# Generated by Django 4.2.5 on 2023-09-14 17:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('product_title', models.CharField(max_length=255)),
                ('product_sku', models.CharField(blank=True, max_length=100)),
                ('product_qty', models.IntegerField(default=0)),
                ('selling_price', models.FloatField(max_length=10)),
                ('discount_price', models.FloatField(blank=True, default=0.0, max_length=255, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('is_verified', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
