# Generated by Django 4.2.5 on 2023-09-17 07:15

from django.db import migrations, models
import util.helper


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to=util.helper.image_path),
        ),
    ]
