# Generated by Django 4.2.5 on 2023-09-17 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_date'], 'verbose_name': 'Products', 'verbose_name_plural': 'Products'},
        ),
    ]
