apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
namespace: savannah
images:
  - name: savannah:latest
    newName: savannah:latest
    newTag: v1
  - name: project_nginx:latest
    newName: savanah-nginx:latest
    newTag: v1
