apiVersion: v1
kind: Service
metadata:
  name: savannah
  namespace: savannah
  labels:
    app: savannah
spec:
  type: LoadBalancer
  ports:
    - name: ngix
      port: 80
      targetPort: 1337
    - name: gunicorn
      port: 8001
      targetPort: 8000
  selector:
    app: savannah