# Generated by Django 4.2.5 on 2023-09-14 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STAFF', 'STAFF'), ('ADMIN', 'ADMIN'), ('SUPER ADMIN', 'SUPER ADMIN'), ('CUSTOMER', 'CUSTOMER')], default='', max_length=20, verbose_name='User role'),
        ),
    ]
