# Generated by Django 4.2.5 on 2023-09-14 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_user_orders_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='status',
            new_name='order_status',
        ),
    ]
