# Generated by Django 4.2.5 on 2023-09-14 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_status_orders_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitems',
            options={'verbose_name': 'Order Items', 'verbose_name_plural': 'Order Items'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Orders', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='purchasedproducts',
            options={'verbose_name': 'Purchased Products', 'verbose_name_plural': 'Purchased Products'},
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_status',
            field=models.CharField(choices=[('ordered', 'Ordered'), ('refunded', 'Refunded order'), ('shipped', 'On shipping'), ('received', 'Order received')], default='ordered', max_length=120, verbose_name='Order status'),
        ),
    ]
