# Generated by Django 4.2.5 on 2023-09-17 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orders_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'ordering': ['-created_at'], 'verbose_name': 'Orders', 'verbose_name_plural': 'Orders'},
        ),
    ]
